name: Update exo docs
on: push
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: install build dependencies
        run: |
          sudo add-apt-repository -y ppa:bluesabre/xfce
          sudo add-apt-repository -y ppa:bluesabre/xfce-development
          sudo apt update
          sudo apt install gtk-doc-tools intltool libglib2.0-dev libgtk-3-dev libtool libxfce4ui-2-dev libxfce4util-dev xfce4-dev-tools

      - name: update doc files
        run: |
          mkdir -p build/
          git clone https://gitlab.xfce.org/xfce/exo.git build/exo
          cd build/exo
          ./autogen.sh --enable-gtk-doc
          make
          cd ../../
          rm -rf exo
          cp -r build/exo/docs/reference/html exo
          rm -rf build/exo
          git status

#      - name: commit
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Update daily-live manifest