name: Update parole docs
on: push
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: install build dependencies
        run: |
          sudo apt update
          sudo apt install gtk-doc-tools intltool libclutter-1.0-dev libclutter-gtk-1.0-dev libdbus-1-dev libdbus-glib-1-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgtk-3-dev libnotify-dev libtagc0-dev libxfce4ui-2-dev libxfconf-0-dev pkg-config xfce4-dev-tools

      - name: update doc files
        run: |
          mkdir -p build/
          git clone https://gitlab.xfce.org/apps/parole.git build/parole
          cd build/parole
          ./autogen.sh --enable-gtk-doc
          make
          cd ../../
          rm -rf parole
          cp -r build/parole/docs/plugin-api/html parole
          rm -rf build/parole
          git status

#      - name: commit
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Update daily-live manifest